import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import { Navigation } from "./ui/Navigation"
import LinkButton from "./ui/LinkButton"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const links: Array<{ href: string; key: string }> = [
  {
    href: "/",
    key: "home",
  },
  {
    href: "/dashboard",
    key: "dashboard",
  },
  {
    href: "/guides",
    key: "guides",
  },
  {
    href: "/login",
    key: "login",
  },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log("rerender root layout")
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div>
            <Navigation links={links} />
            {/* <ul className="flex bg-slate-500">
              {links.map(({ href, key }) => (
                <li className="flex-auto">
                  <Link href={href} key={key}>
                    {key}
                  </Link>
                </li>
              ))}
            </ul> */}
          </div>
        </header>
        <div>
          normal
          <ul className="flex">
            {links.map(({ href, key }) => (
              <li className="flex">
                <LinkButton
                  to={href}
                  replace={false}
                  refresh={false}
                  children={key}
                />
              </li>
            ))}
          </ul>
        </div>
        <div>
          replace
          <ul className="flex">
            {links.map(({ href, key }) => (
              <li className="flex">
                <LinkButton
                  to={href}
                  replace={true}
                  refresh={false}
                  children={key}
                />
              </li>
            ))}
          </ul>
        </div>
        <div>
          refresh
          <ul className="flex">
            {links.map(({ href, key }) => (
              <li className="flex">
                <LinkButton
                  to={href}
                  replace={false}
                  refresh={true}
                  children={key}
                />
              </li>
            ))}
          </ul>
        </div>
        {children}
      </body>
    </html>
  )
}
